### ISSUE TITLE
Lokoja, Nigeria times seem to be inaccurate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#156] opened 2015-06-23 02:02 UTC
```
http://www.islamicfinder.org/prayerDetail.php?latitude=7.8000&longitude=6.7333&t
imezone=1&pmethod=1&fajrTwilight1=10&ishaTwilight=10&fajrTwilight2=10&ishaInterv
al=30&HanfiShafi=1&dhuhrInterval=1&maghribInterval=1&id=25926&daylight=0&prayerC
ustomize=1&city=lokoja&state=41&state_name=Kogi&zipcode=&country=nigeria&day=14&
month=02&year=2015&athan=&aversion=&lang=


```

Original issue reported on code.google.com by `canadai...@gmail.com` on 14 Feb 2015 at 3:27

Attachments:
* [lokoja.7z](https://storage.googleapis.com/google-code-attachments/salat10/issue-156/comment-0/lokoja.7z)
* [IMG_20150212_175433.png](https://storage.googleapis.com/google-code-attachments/salat10/issue-156/comment-0/IMG_20150212_175433.png)
* [IMG_20150213_061948.png](https://storage.googleapis.com/google-code-attachments/salat10/issue-156/comment-0/IMG_20150213_061948.png)

**Comment by canadainc** [comment] 2015-07-28 20:40
Duplicate of Implement Manual DST adjustment #146

**Closed by canadainc** 2015-07-28 20:40 UTC
Labels: Component-Logic, duplicate, Priority-Critical, Type-Defect
