### ISSUE TITLE
Egypt calculations seems to be wrong

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#157] opened 2015-06-23 02:02 UTC
```
Investigate
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 14 Feb 2015 at 3:29

Attachments:
* [egypt.7z](https://storage.googleapis.com/google-code-attachments/salat10/issue-157/comment-0/egypt.7z)

**Comment by canadainc** [comment] 2015-07-29 03:11
Duplicate of Implement Manual DST adjustment #146

**Closed by canadainc** 2015-07-29 03:11 UTC
Labels: Component-Logic, Priority-Critical, Type-Defect
